name: Generate Random Bomberman Graph

on:
  workflow_dispatch:

  schedule:
    - cron: "0 0 * * *"

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install generator
        run: npm install --global pacman-contribution-graph

      - name: Create output folder
        run: mkdir -p dist

      - name: Generate light random Bomberman
        run: >
          pacman-contribution-graph
          --game bomberman
          --username rramadhaan15
          --platform scenario
          --scenario random
          --gameTheme github
          --output dist/bomberman-random.svg

      - name: Generate dark random Bomberman
        run: >
          pacman-contribution-graph
          --game bomberman
          --username rramadhaan15
          --platform scenario
          --scenario random
          --gameTheme github-dark
          --output dist/bomberman-random-dark.svg

      - name: Save animation to output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
